apiVersion: v1
kind: Service 
metadata:
  name: clarify
  labels:
    app: clarfiy
spec:
  type: NodePort
  selector:
    app: clarify-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30002