apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels: 
    type: local
spec: 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: mongo-pv