apiVersion: "v1"
kind: Pod
metadata:
  name: mongodb
  labels: 
    name: mongodb
    app: mongo
spec:
  containers:
    - name: mongo-container
      image: mongo:4.2-bionic
      imagePullPolicy: Always
      ports:
      - containerPort: 27017
        protocol: TCP
      env:
        - name:  MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
        - name: MONGO_INITDB_DATABASE
          value: monogodb