apiVersion: v1
kind: Service
metadata:
  name: django-kube
  labels:
    name: django-kube
    app: django-kube
spec: 
  selector:
    name: django-kube
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8000
      protocol: TCP