apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels: 
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: django
  template:
    metadata:
      labels:
        pod: django
    spec:
      containers:
        - name: django
          image: akshayraina/django_kube_mongo:v36
          ports:
            - containerPort: 8000
          env:  
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: root-user

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: root-password
            
            - name: MONGO_HOST
              value: mongo-service

            - name: REDIS_HOST
              value: redis-service
