apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec: 
  template:
    spec:
      containers:
        - name: django
          image: registry.hub.docker.com/akshayraina/django_kube_mongo:v35
          # image: akshayraina/django_kube_mongo:v22
          command: ['python', 'manage.py', 'makemigrations']
          env:
            # - name: MONGO_INITDB_ROOT_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-credentials
            #       key: root-user

            # - name: MONGO_INITDB_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongo-credentials
            #       key: root-password

            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"

            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"

            - name: MONGO_INITDB_DATABASE
              value: kubernetes_django

            
            # - name: ME_CONFIG_MONGODB_SERVER
            #   valueFrom:
            #     configMapKeyRef:
            #       name: mongodb-configmap
            #       key: database_url

            - name: MONGO_HOST
              value: mongo-service
      restartPolicy: Never
  backoffLimit: 1
