apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:   
    app: nginx
spec:
  selector:
    app: website
  # type: NodePort
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      #nodePort: 30001 